### ISSUE TITLE
Add `files` to package.json.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [helmetjs/content-security-policy-builder#2]
Would prevent `.travis.yaml` and `tests` from being published to NPM.

**Comment by EvanHahn** [comment]
What's the advantage of this over `.npmignore`?

**Comment by wtgtybhertgeghgtwtg** [comment]
One less dotfile, but they're both good.  It's just a whitelist instead of a blacklist, so you wouldn't have to explicitly exclude each file.

**Comment by EvanHahn** [comment]
I think I'd prefer an `.npmignore` to be consistent with the other Helmet projects.

Would you be able to submit a pull request?

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry about the wait.  PR #4.
